# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: create-version-tag
run-name: Tag Master Branch

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Exit if not on master branch
        if: endsWith(github.ref, 'master') == false
        run: exit -1

      - name: Guess Version
        run: |
          echo "PACKAGE_VER=$(cat package.json | jq -r .version).${{github.run_number}}" >> $GITHUB_ENV

      - name: Place ${{ env.PACKAGE_VER }} version tag
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a v${{ env.PACKAGE_VER }} -m "Version ${{ env.PACKAGE_VER }}"
          git push --follow-tags
